trigger:
- none

pool:
  #vmImage: 'ubuntu-latest'
  name: 'Azure Pipelines'




jobs:
- job: HelmDeploy
  displayName: "Helm Deploy to Kubernetes"
  steps:
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'  # Install the latest Helm version
  - task: CmdLine@2
    displayName: "Install Helm Charts"
    inputs:
      script: |
        helm repo add hashicorp https://helm.releases.hashicorp.com
        helm repo update
    
  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'aks-connection'
      namespace: 'vault'
      command: upgrade
      chartType: Name
      chartName: hashicorp/vault
      #chartPath: 
      releaseName: vault
      #valueFile: '$(Build.SourcesDirectory)/values.yaml'
      #valueFile: '$(Build.SourcesDirectory)/values.yaml'
      #install: true
      arguments: '--install --create-namespace --set="ui.enabled=true"'


  - task: KubernetesManifest@0
    displayName: Deploy K8s manifests
    inputs:
      kubernetesServiceConnection: 'aks-connection'
      namespace: vault
      manifests: '$(Build.SourcesDirectory)/vault-ingress/vault-ingress.yaml'
