trigger:
- none

pool:
  #vmImage: 'ubuntu-latest'
  name: 'Azure Pipelines'




jobs:
- job: HelmDeploy
  displayName: "Helm Deploy to Kubernetes"
  steps:
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'  # Install the latest Helm version
  - task: CmdLine@2
    displayName: "Install Helm Charts"
    inputs:
      script: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
    
  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'aks-connection'
      namespace: 'ingress-basic'
      command: upgrade
      chartType: Name
      chartName: ingress-nginx/ingress-nginx
      #chartPath: 
      releaseName: ingress-nginx
      #valueFile: '$(Build.SourcesDirectory)/values.yaml'
      #valueFile: '$(Build.SourcesDirectory)/values.yaml'
      #install: true
      arguments: '--install --create-namespace --set controller.replicaCount=2 --set controller.nodeSelector."kubernetes\.io/os"=linux --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux --set controller.service.externalTrafficPolicy=Local --set controller.service.loadBalancerIP=20.233.26.176'

