
trigger:
- none

pool:
  #vmImage: 'ubuntu-latest'
  name: 'Azure Pipelines'




jobs:
- job: HelmDeploy
  displayName: "Helm Deploy to Kubernetes"
  steps:
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'  # Install the latest Helm version
  - task: CmdLine@2
    displayName: "Install Helm Charts"
    inputs:
      script: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
    
  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'aks-connection'
      namespace: 'monitoring'
      command: upgrade
      chartType: Name
      chartName: prometheus-community/kube-prometheus-stack
      #chartPath: 
      releaseName: monitoring
      arguments: '--install --create-namespace'


  - task: KubernetesManifest@0
    displayName: Deploy K8s manifests
    inputs:
      kubernetesServiceConnection: 'aks-connection'
      namespace: monitoring
      manifests: '$(Build.SourcesDirectory)/monitoring/ingress.yml'
